services:
  - type: web
    name: telegram-loyalty-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: loyalty-bot-db
          property: connectionString

databases:
  - name: loyalty-bot-db
    plan: free
    databaseName: loyaltybot
    user: loyaltyuser